* * *

Creating Variables in R
-----------------------

Variables are containers for storing data values.

R does not have a command for declaring a variable. A variable is created the moment you first assign a value to it. To assign a value to a variable, use the `<-` sign. To output (or print) the variable value, just type the variable name:

In [ ]:
name <- "John"
age <- 40
"Aboozar" -> name2
name   # output "John"
age    # output 40
name2

[1] "John"

[1] 40

[1] "Aboozar"

From the example above, `name` and `age` are **variables**, while `"John"` and `40` are **values**.

In other programming language, it is common to use `=` as an assignment operator. In R, we can use both `=` and `<-` as assignment operators.


However, `<-` is preferred in most cases because the `=` operator can be forbidden in some context in R.


* * *

Print / Output Variables
------------------------

Compared to many other programming languages, you do not have to use a function to print/output variables in R. You can just type the name of the variable:

In [ ]:
#variable declaration
name <- "John Doe"

name # auto-print the value of the name variable

[1] "John Doe"

However, R does have a `print()` function available if you want to use it. This might be useful if you are familiar with other programming languages, such as [Python](https://www.w3schools.com/python/default.asp), which often use a `print()` function to output variables.

In [ ]:
name <- "John Doe"

print(name) # print the value of the name variable

[1] "John Doe"

And there are times you must use the `print()` function to output code, for example when working with `for` loops (which you will learn more about in a later chapter):

In [ ]:
for (x in 1:10) {
  print(x)
}

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5
[1] 6
[1] 7
[1] 8
[1] 9
[1] 10

**Conclusion:** It is up to your if you want to use the `print()` function or not to output code. However, when your code is inside an R expression (for example inside curly braces `{}` like in the example above), use the `print()` function if you want to output the result.

* * *

* * *

Concatenate Elements
--------------------

You can also concatenate, or join, two or more elements, by using the `paste()` function.

To combine both text and a variable, R uses comma (`,`):





* * *

In [1]:
text <- "awesome"

paste("R is", text)

[1] "R is awesome"

You can also use `,` to add a variable to another variable:

In [2]:
text1 <- "R is"
text2 <- "awesome"

paste(text1, text2)

[1] "R is awesome"

For numbers, the `+` character works as a mathematical operator:

In [3]:
num1 <- 5
num2 <- 10

num1 + num2

[1] 15

In [4]:
#strings can not be added using + sign
str1 <- "hello"
str2 <- "bye"

str1 + str2

ERROR: Error in str1 + str2: non-numeric argument to binary operator

If you try to combine a string (text) and a number, R will give you an error:

### Example

num <- 5  
text <- "Some text"

num + text

Result:

`Error in num + text : non-numeric argument to binary operator`

In [6]:
num <- 5
text <- "Some text"

num + text

ERROR: Error in num + text: non-numeric argument to binary operator

**Practice Time**

[Try it Yourself Â»](https://www.w3schools.com/r/tryr.asp?filename=demo_variables_plus2)

###Multiple Variables
R allows you to assign the same value to multiple variables in one line:

In [5]:
# Assign the same value to multiple variables in one line
var1 <- var2 <- var3 <- "Orange"

# Print variable values
var1
var2
var3

[1] "Orange"

[1] "Orange"

[1] "Orange"

* * *

Variable Names
--------------

A variable can have a short name (like x and y) or a more descriptive name (age, carname, total\_volume). Rules for R variables are:

*   A variable name must start with a letter and can be a combination of letters, digits, period(.)  
    and underscore(\_). If it starts with period(.), it cannot be followed by a digit.
*   A variable name cannot start with a number or underscore (\_)
*   Variable names are case-sensitive (age, Age and AGE are three different variables)
*   Reserved words cannot be used as variables (TRUE, FALSE, NULL, if...)

```r
# Legal variable names:
myvar <- "John"  
my\_var <- "John"  
myVar <- "John"  
MYVAR <- "John"  
myvar2 <- "John"  
.myvar <- "John"

# Illegal variable names:
2myvar <- "John"  
my-var <- "John"  
my var <- "John"  
\_my\_var <- "John"  
my\_v@ar <- "John"  
TRUE <- "John"
```

<mark>Remember that variable names are case-sensitive!</mark>

* * *

Data Types
----------

In programming, data type is an important concept.

Variables can store data of different types, and different types can do different things.

In R, variables do not need to be declared with any particular type, and can even change type after they have been set:

R has a variety of data types and object classes. You will learn much more about these as you continue to get to know R.

* * *

In [7]:
my_var1 <- 30  # my_var is type of numeric
my_var2 <- "Sally" # my_var is now of type character (aka string)

my_var1 # print my_var
my_var2

[1] 30

[1] "Sally"

Basic Data Types
----------------

Basic data types in R can be divided into the following types:

*   `numeric` - (10.5, 55, 787)
*   `integer` - (1L, 55L, 100L, where the letter "L" declares this as an integer)
*   `complex` - (9 + 3i, where "i" is the imaginary part)
*   `character` (a.k.a. string) - ("k", "R is exciting", "FALSE", "11.5")
*   `logical` (a.k.a. boolean) - (TRUE or FALSE)

We can use the `class()` function to check the data type of a variable:

### Example
```
x <- 10.5  
class(x)

x <- 1000L  
class(x)

x <- 9i + 3  
class(x)  
  
x <- "R is exciting"  
class(x)  
  
x <- TRUE  
class(x)
```

In [10]:
x <- 10.5
class(x)

x <- 1000L
class(x)

x <- 9i + 3
class(x)

x <- "R is exciting"
class(x)

x <- TRUE
class(x)

[1] "numeric"

[1] "integer"

[1] "complex"

[1] "character"

[1] "logical"

[Try it Yourself Â»](https://www.w3schools.com/r/tryr.asp?filename=demo_data_types)

You will learn much more about the individual data types in the upcoming chapters.

***

* * *

Numbers
-------

There are three number types in R:

*   `numeric`
*   `integer`
*   `complex`

Variables of number types are created when you assign a value to them:

### Example
```

x <- 10.5   # numeric
y <- 10L    # integer
z <- 1i     # complex
```
* * *

In [18]:
x <- 10.5   # numeric
y <- 10L    # integer (Long)
z <- 1i     # complex

In [19]:
class(x)
class(y)
class(z)

[1] "numeric"

[1] "integer"

[1] "complex"

Numeric
-------

A `numeric` data type is the most common type in R, and contains any number with or without a decimal, like: 10.5, 55, 787:

* * *

In [11]:
x <- 10.5
y <- 55

# Print values of x and y
x
y

# Print the class name of x and y
class(x)
class(y)

[1] 10.5

[1] 55

[1] "numeric"

[1] "numeric"

Integer
-------

Integers are numeric data without decimals. This is used when you are certain that you will never create a variable that should contain decimals. To create an `integer` variable, in the older versions of R you were required to use the letter `L` after the integer value: In most cases, you can omit the L suffix for integers in modern R.

* * *

In [14]:
x <- 1000L
y <- 55L

# Print values of x and y
x
y

# Print the class name of x and y
class(x)
class(y)

[1] 1000

[1] 55

[1] "integer"

[1] "integer"

* * *

Complex
-------

A `complex` number is written with an "`i`" as the imaginary part:

* * *

In [17]:
x <- 3+5i
y <- 5i

# Print values of x and y
x
y

# Print the class name of x and y
class(x)
class(y)

[1] 3+5i

[1] 0+5i

[1] "complex"

[1] "complex"

Type Conversion
---------------

You can convert from one type to another with the following functions:

*   `as.numeric()`
*   `as.integer()`
*   `as.complex()`

### Example
```
x <- 1L # integer
y <- 2 # numeric

# convert from integer to numeric:
a <- as.numeric(x)

# convert from numeric to integer:
b <- as.integer(y)

# print values of x and y
x
y

# print the class name of a and b
class(a)
class(b)
```
[Try it Yourself Â»](https://www.w3schools.com/r/tryr.asp?filename=demo_numbers_convert)

  
***

In [32]:
ifÂ (ageÂ >Â 18)
Â Â Â Â print("YouÂ areÂ anÂ adult.")
else
Â Â Â Â print("YouÂ areÂ notÂ anÂ adult.")

ERROR: Error in parse(text = x, srcfile = src): <text>:1:3: unexpected input
1: ifÂ
      ^

In [30]:
age <- 30
weight <- 70L
name <- "Alice"
is_student <- TRUE


height_estimate <- age + weight
circumference <- 2 * pi * weight / 2
weight * height_estimate
pi * (weight / 2)^2
print(height_estimate)
print(circumference)

[1] 7000

[1] 3848.451

[1] 100
[1] 219.9115

##Exercises on Variables, DataType, Numbers

**Exercise 1: Variable Declarations and Data Types**

1. **Create different types of variables:**
   - Numeric: `age <- 30`
   - Integer: `weight <- 70L` (or simply `weight <- 70`)
   - Character (string): `name <- "Alice"`
   - Logical (boolean): `is_student <- TRUE`
2. **Check their data types:**
   ```R
   class(age)
   class(weight)
   class(name)
   class(is_student)
   ```
3. **Modify variable values and observe data type changes:**
   - Age to a decimal number: `age <- 30.5`
   - Convert weight to character: `weight <- as.character(weight)`

**Explanation:**

- Variables store data values.
- Data types categorize the kinds of data variables can hold (numeric, integer, etc.).
- Learn `class()` to determine a variable's data type.
- Data types can sometimes change (e.g., integer to character using conversion).

**Exercise 2: Basic Calculations and Output**

1. **Perform calculations:**
   - Add age and weight: `height_estimate <- age + weight`
   - Calculate circumference (assuming 2 * pi * radius): `circumference <- 2 * pi * weight / 2` (note the conversion to numeric for `pi`)
2. **Print results:**
   ```R
   print(height_estimate)
   print(circumference)
   ```
3. **Experiment with different calculations and data:**
   - Calculate area using `weight * height_estimate` or `pi * (weight / 2)^2`

**Explanation:**

- R performs calculations like other programming languages using operators (+, -, *, /).
- `print()` displays the value, but variables themselves display their values when directly executed.
- Be mindful of data types and conversions needed for certain operations.

**Exercise 3: Strings and Concatenation**

1. **Create strings:**
   - Favorite color: `color <- "Blue"`
   - Favorite food: `food <- "Pizza"`
2. **Concatenate strings:**
   - Use `paste()` to combine strings and variables:
     ```R
     print(paste0("My favorite color is ", color, "."))
     print(paste("My favorite food is", food, "!", sep = ""))
     ```
3. **Experiment with different separators and formatting:**
   - Try `sep = " - "` for a space-dash separator.
   - Include numbers (e.g., `paste("I am", age, "years old.")`)

**Explanation:**

- Strings hold textual data enclosed in quotes.
- `paste()` joins strings, numbers, or variables according to the `sep` argument.
- Explore different ways to combine and format strings.

**Exercise 4: Conditional Statements**

1. **Check if the age is above 18:**
   ```R
   if (age > 18) {
       print("You are an adult.")
   } else {
       print("You are not an adult.")
   }
   ```
2. **Check if the age is an even number and print a message accordingly.**
3. **Modify the conditions to explore different scenarios.**

**Explanation:**

- Conditional statements (`if`, `else if`, `else`) make decisions based on conditions.
- The code executes the block within `if` if the condition is true, and the `else` block if it's false.
- Use comparison operators like `>`, `<`, `==`, etc. within the conditions.

**Exercise 5: Loops (Optional)**

1. **Count from 1 to 10:**
   ```R
   for (i in 1:10) {
       print(i)
   }
   ```
2. **Iterate over a list of names:**
   ```R
   names <- c("Alice", "Bob", "Charlie")
   for (name in names) {
       print(paste0("Hello, ", name, "!"))
   }
   ```
3. **Modify the loops to change the behavior (e.g., count backwards, skip numbers).**

**Explanation:**

- Loops repeat a block of code multiple times.
- `for` loops iterate a certain number of times (based on the range within `:`).
- They're useful for automating repetitive tasks.

These exercises provide a stepping stone to learn R's basic concepts. Remember to practice regularly

##Exercises on Variables, DataType, Numbers

**Exercise 1: Variable Declarations and Data Types**

1. **Create different types of variables:**
   - Numeric: `age <- 30`
   - Integer: `weight <- 70L` (or simply `weight <- 70`)
   - Character (string): `name <- "Alice"`
   - Logical (boolean): `is_student <- TRUE`
2. **Check their data types:**
   ```R
   class(age)
   class(weight)
   class(name)
   class(is_student)
   ```
3. **Modify variable values and observe data type changes:**
   - Age to a decimal number: `age <- 30.5`
   - Convert weight to character: `weight <- as.character(weight)`

**Explanation:**

- Variables store data values.
- Data types categorize the kinds of data variables can hold (numeric, integer, etc.).
- Learn `class()` to determine a variable's data type.
- Data types can sometimes change (e.g., integer to character using conversion).

**Exercise 2: Basic Calculations and Output**

1. **Perform calculations:**
   - Add age and weight: `height_estimate <- age + weight`
   - Calculate circumference (assuming 2 * pi * radius): `circumference <- 2 * pi * weight / 2` (note the conversion to numeric for `pi`)
2. **Print results:**
   ```R
   print(height_estimate)
   print(circumference)
   ```
3. **Experiment with different calculations and data:**
   - Calculate area using `weight * height_estimate` or `pi * (weight / 2)^2`

**Explanation:**

- R performs calculations like other programming languages using operators (+, -, *, /).
- `print()` displays the value, but variables themselves display their values when directly executed.
- Be mindful of data types and conversions needed for certain operations.

**Exercise 3: Strings and Concatenation**

1. **Create strings:**
   - Favorite color: `color <- "Blue"`
   - Favorite food: `food <- "Pizza"`
2. **Concatenate strings:**
   - Use `paste()` to combine strings and variables:
     ```R
     print(paste0("My favorite color is ", color, "."))
     print(paste("My favorite food is", food, "!", sep = ""))
     ```
3. **Experiment with different separators and formatting:**
   - Try `sep = " - "` for a space-dash separator.
   - Include numbers (e.g., `paste("I am", age, "years old.")`)

**Explanation:**

- Strings hold textual data enclosed in quotes.
- `paste()` joins strings, numbers, or variables according to the `sep` argument.
- Explore different ways to combine and format strings.

**Exercise 4: Conditional Statements**

1. **Check if the age is above 18:**
   ```R
   if (age > 18) {
       print("You are an adult.")
   } else {
       print("You are not an adult.")
   }
   ```
2. **Check if the age is an even number and print a message accordingly.**
3. **Modify the conditions to explore different scenarios.**

**Explanation:**

- Conditional statements (`if`, `else if`, `else`) make decisions based on conditions.
- The code executes the block within `if` if the condition is true, and the `else` block if it's false.
- Use comparison operators like `>`, `<`, `==`, etc. within the conditions.

**Exercise 5: Loops (Optional)**

1. **Count from 1 to 10:**
   ```R
   for (i in 1:10) {
       print(i)
   }
   ```
2. **Iterate over a list of names:**
   ```R
   names <- c("Alice", "Bob", "Charlie")
   for (name in names) {
       print(paste0("Hello, ", name, "!"))
   }
   ```
3. **Modify the loops to change the behavior (e.g., count backwards, skip numbers).**

**Explanation:**

- Loops repeat a block of code multiple times.
- `for` loops iterate a certain number of times (based on the range within `:`).
- They're useful for automating repetitive tasks.

These exercises provide a stepping stone to learn R's basic concepts. Remember to practice regularly

In [16]:
x <- 1L # integer
y <- 2 # numeric

# convert from integer to numeric:
a <- as.numeric(x)

# convert from numeric to integer:
b <- as.integer(y)

# print values of x and y
x
y

# print the class name of a and b
class(a)
class(b)

[1] 1

[1] 2

[1] "numeric"

[1] "integer"

##Exercises on Variables, DataType, Numbers

**Exercise 1: Variable Declarations and Data Types**

1. **Create different types of variables:**
   - Numeric: `age <- 30`
   - Integer: `weight <- 70L` (or simply `weight <- 70`)
   - Character (string): `name <- "Alice"`
   - Logical (boolean): `is_student <- TRUE`
2. **Check their data types:**
   ```R
   class(age)
   class(weight)
   class(name)
   class(is_student)
   ```
3. **Modify variable values and observe data type changes:**
   - Age to a decimal number: `age <- 30.5`
   - Convert weight to character: `weight <- as.character(weight)`

**Explanation:**

- Variables store data values.
- Data types categorize the kinds of data variables can hold (numeric, integer, etc.).
- Learn `class()` to determine a variable's data type.
- Data types can sometimes change (e.g., integer to character using conversion).

**Exercise 2: Basic Calculations and Output**

1. **Perform calculations:**
   - Add age and weight: `height_estimate <- age + weight`
   - Calculate circumference (assuming 2 * pi * radius): `circumference <- 2 * pi * weight / 2` (note the conversion to numeric for `pi`)
2. **Print results:**
   ```R
   print(height_estimate)
   print(circumference)
   ```
3. **Experiment with different calculations and data:**
   - Calculate area using `weight * height_estimate` or `pi * (weight / 2)^2`

**Explanation:**

- R performs calculations like other programming languages using operators (+, -, *, /).
- `print()` displays the value, but variables themselves display their values when directly executed.
- Be mindful of data types and conversions needed for certain operations.

**Exercise 3: Strings and Concatenation**

1. **Create strings:**
   - Favorite color: `color <- "Blue"`
   - Favorite food: `food <- "Pizza"`
2. **Concatenate strings:**
   - Use `paste()` to combine strings and variables:
     ```R
     print(paste0("My favorite color is ", color, "."))
     print(paste("My favorite food is", food, "!", sep = ""))
     ```
3. **Experiment with different separators and formatting:**
   - Try `sep = " - "` for a space-dash separator.
   - Include numbers (e.g., `paste("I am", age, "years old.")`)

**Explanation:**

- Strings hold textual data enclosed in quotes.
- `paste()` joins strings, numbers, or variables according to the `sep` argument.
- Explore different ways to combine and format strings.

**Exercise 4: Conditional Statements**

1. **Check if the age is above 18:**
   ```R
   if (age > 18) {
       print("You are an adult.")
   } else {
       print("You are not an adult.")
   }
   ```
2. **Check if the age is an even number and print a message accordingly.**
3. **Modify the conditions to explore different scenarios.**

**Explanation:**

- Conditional statements (`if`, `else if`, `else`) make decisions based on conditions.
- The code executes the block within `if` if the condition is true, and the `else` block if it's false.
- Use comparison operators like `>`, `<`, `==`, etc. within the conditions.

**Exercise 5: Loops (Optional)**

1. **Count from 1 to 10:**
   ```R
   for (i in 1:10) {
       print(i)
   }
   ```
2. **Iterate over a list of names:**
   ```R
   names <- c("Alice", "Bob", "Charlie")
   for (name in names) {
       print(paste0("Hello, ", name, "!"))
   }
   ```
3. **Modify the loops to change the behavior (e.g., count backwards, skip numbers).**

**Explanation:**

- Loops repeat a block of code multiple times.
- `for` loops iterate a certain number of times (based on the range within `:`).
- They're useful for automating repetitive tasks.

These exercises provide a stepping stone to learn R's basic concepts. Remember to practice regularly

##Solution to the Exercises on Variable, DataTypes, Numbers


**Exercise 1: Variable Declarations and Data Types**

```r
# Create variables of different data types
age <- 30        # Numeric (whole or decimal numbers)
weight <- 70L     # Integer (whole numbers, use L for older R versions)
name <- "Alice"  # Character (string of text)
is_student <- TRUE # Logical (TRUE or FALSE)

# Check the data types of each variable
class(age)   # Output: "numeric"
class(weight) # Output: "integer" or "numeric" depending on your R version
class(name)   # Output: "character"
class(is_student) # Output: "logical"

# Modify values and observe data type changes
age <- 30.5   # Now age is a decimal number
class(age)    # Output: "numeric"

weight <- as.character(weight) # Convert weight to a string
class(weight) # Output: "character"

# Remember, data types can sometimes change!
```

**Explanation:**

- We create variables using `<-` and assign them values of different data types.
- `class()` function reveals the data type of each variable.
- Modify values and use `class()` again to see how data types can change.

**Exercise 2: Basic Calculations and Output**

```r
# Perform calculations
height_estimate <- age + weight  # Estimate height based on age and weight
circumference <- 2 * pi * weight / 2  # Calculate circumference (assuming 2 * pi * radius)

# Convert pi to numeric, as calculations usually operate on numeric values
pi <- as.numeric(pi)

# Print the results
print(height_estimate)  # Output: The estimated height
print(circumference)   # Output: The calculated circumference

# Experiment with different calculations and data!
area <- weight * height_estimate   # Calculate area using estimated height
pi_squared <- pi^2                   # Calculate pi squared
another_area <- pi_squared * (weight / 2)^2  # Calculate area using radius and pi
print(area)
print(another_area)
```

**Explanation:**

- We perform calculations using basic arithmetic operators (+, -, *, /).
- Remember to use numeric data types for calculations (convert `pi` here).
- `print()` displays the results, but variables themselves show their values directly.
- Explore different formulas and data to practice calculations.

**Exercise 3: Strings and Concatenation**

```r
# Create strings
color <- "Blue"
food <- "Pizza"

# Use paste() to combine strings and variables
print(paste0("My favorite color is ", color, "."))  # Output: "My favorite color is Blue."
print(paste("My favorite food is", food, "!", sep = ""))  # Output: "My favorite food isPizza!"

# Experiment with different separators and formatting
print(paste("My favorite color is", color, ".", sep = " - "))  # Output: "My favorite color is - Blue."
print(paste("I am", age, "years old."))  # Output: "I am 30.5 years old."
```

**Explanation:**

- Strings are text enclosed in quotes.
- `paste()` joins strings, numbers, and variables with a specified separator (`sep`).
- Explore different formatting options using `sep` and combining elements.

**Exercise 4: Conditional Statements**

```r
# Check if age is above 18
if (age > 18) {
    print("You are an adult.")
} else {
    print("You are not an adult.")
}

# Check if age is even and print a message accordingly
if (age %% 2 == 0) {
    print("Your age is an even number.")
} else {
    print("Your age is an odd number.")
}

# Modify conditions to explore different scenarios!
if (weight > 60 & is_student) {
    print("You are likely a tall student.")
} elif (height_estimate > 170) {
    print("You might be above average height.")
} else {
    print("You have interesting data, explore further!")
}
```

**Explanation:**

- `if` and `else` statements make decisions based on conditions.
- The code within `if` executes if the condition is true, otherwise `else` runs.
- Use comparison operators like `>`, `<`, `==`, etc. in conditions.
- Modify conditions to create more complex decision-making logic.
- The previous response already demonstrated how to use `if` and `else` statements.
- This exercise encourages you to experiment with more complex conditions and nested statements.
- Try combining conditions using `&` (AND) and `|` (OR), and nesting `if` statements within others.
- For example, check if someone is an adult and a student simultaneously using `if (age > 18 & is_student)`.

**Exercise 5: Loops (Optional)**

```r
# Count from 1 to 10 using a loop
for (i in 1:10) {
    print(i)
}

# Iterate over a list of names and print greetings
names <- c("Alice", "Bob", "Charlie")
for (name in names) {
    print(paste0("Hello, ", name, "!"))
}

# Modify loops to change behavior (e.g., count backwards, skip numbers)
# Example: count backwards from 10 to 1
for (i in 10:1) {
    print(i)
}

# Example: skip even numbers from 1 to 10
for (i in 1:10) {
    if (i %% 2 != 0) {  # Check if i is odd (not divisible by 2)
        print(i)
    }
}
```

**Explanation:**

- `for` loops repeat a block of code a certain number of times.
- The `in` operator specifies the range or sequence for iteration.
- Modify the range and conditions within the loop to achieve different behaviors.
- Explore other loop types like `while` and `repeat` for more control over iterations.

Remember that these exercises are just a starting point. Feel free to experiment, try new things, and explore other R concepts to deepen your understanding!

##R Math
* * *

Simple Math
-----------

In R, you can use **operators** to perform common mathematical operations on numbers.

The `+` operator is used to add together two values:

In [34]:
10 + 5

[1] 15

And the `-` operator is used for subtraction:

* * *

In [35]:
10 - 5

[1] 5

<mark>You will learn more about available operators in our [R Operators Tutorial](https://www.w3schools.com/r/r_operators.asp)</mark>.

Built-in Math Functions
-----------------------

R also has many built-in math functions that allows you to perform mathematical tasks on numbers.

For example, the `min()` and `max()` functions can be used to find the lowest or highest number in a set:

* * *

In [39]:
max(5, 10, 15)

min(5, 10, 15)

[1] 15

[1] 5

* * *

sqrt()
------

The `sqrt()` function returns the square root of a number:

* * *

In [40]:
sqrt(16)

[1] 4

abs()
-----

The `abs()` function returns the absolute (positive) value of a number:

* * *

In [38]:
abs(-4.7)

[1] 4.7

ceiling() and floor()
---------------------

The `ceiling()` function rounds a number upwards to its nearest integer, and the `floor()` function rounds a number downwards to its nearest integer, and returns the result:

  
***

In [41]:
ceiling(1.4)

floor(1.4)

[1] 2

[1] 1

#R Strings
* * *

String Literals
---------------

Strings are used for storing text.

A string is surrounded by either single quotation marks, or double quotation marks:

`"hello"` is the same as `'hello'`:

* * *

In [42]:
"hello"
'hello'

[1] "hello"

[1] "hello"

Assign a String to a Variable
-----------------------------

Assigning a string to a variable is done with the variable followed by the `<-` operator and the string:

* * *

In [43]:
str <- "Hello"
str # print the value of str

[1] "Hello"


Multiline Strings
-----------------

You can assign a multiline string to a variable like this:

### Example
```
str <- "Lorem ipsum dolor sit amet,
consectetur adipiscing elit,
sed do eiusmod tempor incididunt
ut labore et dolore magna aliqua."

str # print the value of str
```
[Try it Yourself Â»](https://www.w3schools.com/r/tryr.asp?filename=demo_strings_multi)


* * *

In [46]:
str <- "Lorem ipsum dolor sit amet,
consectetur adipiscing elit,
sed do eiusmod tempor incididunt
ut labore et dolore magna aliqua."

str # print the value of str

[1] "Lorem ipsum dolor sit amet,\nconsectetur adipiscing elit,\nsed do eiusmod tempor incididunt\nut labore et dolore magna aliqua."

However, note that R will add a "**\\n**" at the end of each line break. This is called an escape character, and the **n** character indicates a **new line**.

If you want the line breaks to be inserted at the same position as in the code, use the `cat()` function:

### Example

```
str <- "Lorem ipsum dolor sit amet,
consectetur adipiscing elit,
sed do eiusmod tempor incididunt
ut labore et dolore magna aliqua."

cat(str)
```

[Try it Yourself Â»](https://www.w3schools.com/r/tryr.asp?filename=demo_strings_multi2)

* * *

In [45]:
str <- "Lorem ipsum dolor sit amet,
consectetur adipiscing elit,
sed do eiusmod tempor incididunt
ut labore et dolore magna aliqua."

cat(str)

Lorem ipsum dolor sit amet,
consectetur adipiscing elit,
sed do eiusmod tempor incididunt
ut labore et dolore magna aliqua.


* * *

String Length
-------------

There are many usesful string functions in R.

For example, to find the number of characters in a string, use the `nchar()` function:

* * *

In [47]:
str <- "Hello World!"

nchar(str)

[1] 12

Check a String
--------------

Use the `grepl()` function to check if a character or a sequence of characters are present in a string:

### Example
```
str <- "Hello World!"

grepl("H", str)
grepl("Hello", str)
grepl("X", str)
```
[Try it Yourself Â»](https://www.w3schools.com/r/tryr.asp?filename=demo_strings_grepl)

* * *

In [48]:
str <- "Hello World!"

grepl("H", str)
grepl("Hello", str)
grepl("X", str)

[1] TRUE

[1] TRUE

[1] FALSE

Combine Two Strings
-------------------

Use the `paste()` function to merge/concatenate two strings:

In [49]:
str1 <- "Hello"
str2 <- "World"

paste(str1, str2)

[1] "Hello World"

#R Escape Characters

* * *

Escape Characters
-----------------

To insert characters that are illegal in a string, you must use an escape character.

An escape character is a backslash `\` followed by the character you want to insert.

An example of an illegal character is a double quote inside a string that is surrounded by double quotes:

### Example
```
str <- "We are the so-called "Vikings", from the north."

str
```
#### Result:

`Error: unexpected symbol in "str <- "We are the so-called "Vikings"`

[Try it Yourself Â»](https://www.w3schools.com/r/tryr.asp?filename=demo_strings_esc)

To fix this problem, use the escape character `\"`:

### Example

The escape character allows you to use double quotes when you normally would not be allowed:
```
str <- "We are the so-called \"Vikings\", from the north."

str
cat(str)
```
[Try it Yourself Â»](https://www.w3schools.com/r/tryr.asp?filename=demo_strings_esc2)

In [50]:
str <- "We are the so-called \"Vikings\", from the north."

str
cat(str)

[1] "We are the so-called \"Vikings\", from the north."

We are the so-called "Vikings", from the north.

<mark>Note that auto-printing the **str** variable will print the backslash in the output (This may not be true in all environments though). You can use the `cat()` function to print it without backslash.</mark>

Other escape characters in R:

| Code | Result |
| --- | --- |
| \\\\ | Backslash |
| \\n | New Line |
| \\r | Carriage Return |
| \\t | Tab |
| \\b | Backspace |

* * *

Booleans (Logical Values)
-------------------------

In programming, you often need to know if an expression is **true** or **false**.

You can evaluate any expression in R, and get one of two answers, `TRUE` or `FALSE`.

When you compare two values, the expression is evaluated and R returns the logical answer:

In [51]:
10 > 9    # TRUE because 10 is greater than 9
10 == 9   # FALSE because 10 is not equal to 9
10 < 9    # FALSE because 10 is greater than 9

[1] TRUE

[1] FALSE

[1] FALSE

You can also compare two variables:

In [52]:
a <- 10
b <- 9

a > b

[1] TRUE

You can also run a condition in an `if` statement, which you will learn much more about in the [if..else](https://www.w3schools.com/r/r_if_else.asp) chapter.

### Example

```
a <- 200
b <- 33

if (b > a) {
  print ("b is greater than a")
} else {
  print("b is not greater than a")
}
```

[Try it Yourself Â»](https://www.w3schools.com/r/tryr.asp?filename=demo_booleans_if)

***

In [53]:
a <- 200
b <- 33

if (b > a) {
  print ("b is greater than a")
} else {
  print("b is not greater than a")
}

[1] "b is not greater than a"

##Exercises on Maths, Strings and Escape Character

Please attempt the following exercises. Wait for Ali to let you know which ones to attempt or aim to attempt all if you are ahead.

**Exercise 1: Simple Math Operations**

1. **Create code cells below:** For all the exercises below. Generate a new cell code adn add any comments where necessary to explain what you are doing.
2. **Add numbers:** Type `5 + 3` and press Enter. Observe the output (8). Try other additions like `10 + 20` and `7 - 4`.
3. **Multiply and divide:** Try `4 * 5` and `12 / 3`. Explore combining operations like `10 / 2 * 3`.
4. **Order of operations:** Remember "PEMDAS" (Parentheses, Exponents, Multiplication/Division, Addition/Subtraction). Experiment with parentheses to change the order.
5. **Challenge:** Create a short calculation to find the area of a rectangle with a width of 6 and a height of 8 (use multiplication).

**Exercise 2: Built-in Math Functions**

1. **Find the largest of 3 numbers:** Type `max(12, 15, 7)` and press Enter. The output (15) shows the largest value.
2. **Find the smallest:** Use `min(12, 6, 20)` to see the smallest number.
3. **Square root:** Calculate the square root of 25 with `sqrt(25)`. The answer (5) represents the side length of a square with an area of 25.
4. **Absolute value:** Use `abs(-8)` to get the positive version, which is 8. Try with negative and positive numbers.
5. **Challenge:** Combine functions and operations. How many seconds are in 3 minutes? Use `60 * 3`.

**Exercise 3: Working with Strings**

1. **Create strings:** Type `"Hello!"` and press Enter. The output shows the string in quotes. Try other messages like `"How are you?"`.
2. **Assign to a variable:** Assign a string to a variable using `message <- "Welcome"`. Print the variable with `message`.
3. **String length:** Find the number of characters in "Happy coding!" using `nchar("Happy coding!")`.
4. **Check for characters:** Use `grepl("o", "coding")` to see if "o" exists (TRUE). Try "x" instead (FALSE).
5. **Combine strings:** Join "Hello" and "World" with `paste("Hello", "World")`. Experiment with separators like `paste("Hello", "World", sep = "-")`.

**Exercise 4: Escape Characters**

1. **Double quotes within a string:** Try `"He said "Hi!"`. This won't work.
2. **Use escape character:** Fix it with `message <- "He said \"Hi!\""`. Print `message` to see the correct output.
3. **Other escape characters:** Try `cat("\tThis is tabbed.")` to see the tab (\t) effect. Explore `\\n` for a new line and `\\b` for backspace.
4. **Practice:** Create a string with a sentence that requires different escape characters, and make it print correctly using `cat()`.

**Exercise 5: Boolean Values (TRUE/FALSE)**

1. **Comparison:** Type `7 > 5` and press Enter. The output (TRUE) indicates 7 is greater than 5. Try `3 < 9` and `10 == 10`.
2. **Variables:** Assign numbers to `a` and `b`, like `a <- 12` and `b <- 8`. Compare them with `a > b`.
3. **Logical operators:** Combine comparisons with `&` (AND) and `|` (OR). For example, `a > 5 & b < 10` checks both conditions.
4. **`if` statements:** Use `if (a > 10) { print("a is greater than 10") }` to conditionally execute code based on a condition.
5. **Challenge:** Use boolean logic to check if a number is even (divisible by 2) using `if` and the modulo operator (`%%`).

Remember to run each code snippet you write and experiment with different values to practice! Happy learning!

In [59]:
message <- "Welcome"
print("message")

[1] "message"

In [55]:
max(12, 15, 7)

[1] 15

In [54]:
5+3

[1] 8

##Solutions to Exercises on Maths, Strings and Escape Character



**Exercise 1: Simple Math Operations**

**Explanation:**

- **Lines 1 & 2:** Perform basic addition, observing the output (8). Explore other additions (`10 + 20`, `7 - 4`).
- **Lines 3 & 4:** Multiply and divide, understanding the order of operations (PEMDAS). Experiment with combining operations.
- **Line 5:** Calculate rectangle area using multiplication (`6 * 8 = 48`). You can adjust the numbers for practice.

```R
# Open RStudio and create a new script.

# Line 1: Add two numbers
5 + 3  # Output: 8

# Line 2: More additions
10 + 20  # Output: 30
7 - 4    # Output: 3

# Line 3: Multiplication and division
4 * 5     # Output: 20
12 / 3    # Output: 4

# Line 4: Combine operations
10 / 2 * 3  # Output: 15 (PEMDAS: division before multiplication)

# Line 5: Rectangle area
width <- 6
height <- 8
area <- width * height
print(paste0("Rectangle area:", area))  # Output: Rectangle area: 48
```

**Exercise 2: Built-in Math Functions**

**Explanation:**

- **Lines 1 & 2:** Find the maximum/minimum of 3 numbers using `max()` and `min()`.
- **Lines 3 & 4:** Calculate square root with `sqrt()` and absolute value with `abs()`. Understand their meanings.
- **Line 5:** Convert minutes to seconds using multiplication (`60 * 3 = 180`).

```R
# Line 1: Find the largest number
max(12, 15, 7)  # Output: 15

# Line 2: Find the smallest number
min(12, 6, 20)  # Output: 6

# Line 3: Square root
sqrt(25)  # Output: 5

# Line 4: Absolute value
abs(-8)   # Output: 8 (positive version)

# Line 5: Minutes to seconds
minutes <- 3
seconds <- 60 * minutes
print(paste0(minutes, "minutes is", seconds, "seconds."))  # Output: 3 minutes is 180 seconds.
```

**Exercise 3: Working with Strings**

**Explanation:**

- **Lines 1 & 2:** Create strings in quotes and assign them to variables for clarity. Use `print()` to display them.
- **Lines 3 & 4:** Find the string length and check for characters using `nchar()` and `grepl()`.
- **Line 5:** Combine strings with `paste()`, experimenting with separators.

```R
# Line 1: Create a string
message <- "Hello!"
print(message)  # Output: Hello!

# Line 2: Assign to a variable
greeting <- "Have a great day!"
print(greeting)  # Output: Have a great day!

# Line 3: String length
name <- "R learner"
nchar(name)  # Output: 9 (including the space)

# Line 4: Check for characters
grepl("a", name)  # Output: TRUE
grepl("z", name)  # Output: FALSE

# Line 5: Combine strings
full_message <- paste(greeting, name)
print(full_message)  # Output: Have a great day! R learner

# Separator example
combined_words <- paste("apple", "orange", "banana", sep = ", ")
print(combined_words)  # Output: apple, orange, banana
```

**Exercise 4: Escape Characters**

**Explanation:**

- **Lines 1 & 2:** Demonstrate the error with double quotes, then fix it using the escape character (`\"`).
- **Lines 3 & 4:** Introduce other escape characters (`\t`, `\n`, `\b`) and practice using them correctly.

```R
# Line 1: Invalid string (missing escape character)
print("He said "Hi!")  # This will cause an error

# Line 2: Fixed string with escape character
message <- "He said \"Hi!\""
print(message)  # Output: He said "Hi!"

# Line 3: Tab example
print("\tThis is tabbed.")  # Output:   This is tab
```

#R Operators
* * *

Operators
---------

Operators are used to perform operations on variables and values.

In the example below, we use the `+` operator to add together two values:

In [ ]:
10 + 5

[1] 15


R divides the operators in the following groups:

*   Arithmetic operators
*   Assignment operators
*   Comparison operators
*   Logical operators
*   Miscellaneous operators

* * *

R Arithmetic Operators
----------------------

Arithmetic operators are used with numeric values to perform common mathematical operations:

* * *


 **Operator** | **Name**                            | **Example**
--------------|-------------------------------------|-------------
 **\+**       | Addition                            | x \+ y      
 **\-**       | Subtraction                         | x \- y      
 **\***       | Multiplication                      | x \* y      
 **/**        | Division                            | x / y       
 **^**        | Exponent                            | x ^ y       
 **%%**       | Modulus \(Remainder from division\) | x %% y      
 **%/%**      | Integer Division                    | x%/%y       


To practice these please visit: [R Aritthmatic operators](https://www.w3schools.com/r/r_operators.asp#:~:text=R%20Arithmetic%20Operators)

R Assignment Operators
----------------------

Assignment operators are used to assign values to variables:

```
my_var <- 3

my_var <<- 3

3 -> my_var

3 ->> my_var

my_var # print my_var
```

**Note:** `<<-` is a global assigner. You will learn more about this in the [Global Variable chapter](https://www.w3schools.com/r/r_variables_global.asp).

It is also possible to turn the direction of the assignment operator.

x <- 3 is equal to 3 -> x


* * *

In [ ]:
my_var <- 3

my_var <<- 3

3 -> my_var

3 ->> my_var

my_var # print my_var

[1] 3

R Comparison Operators
----------------------

Comparison operators are used to compare two values:

To practice these please visit: [Comparison Operator](https://www.w3schools.com/r/r_operators.asp#:~:text=R%20Comparison%20Operators)

* * *

R Logical Operators
-------------------

Logical operators are used to combine conditional statements:

| Operator | Description |
| --- | --- |
| & | Element-wise Logical AND operator. It returns TRUE if both elements are TRUE |
| && | Logical AND operator - Returns TRUE if both statements are TRUE |
| | | Elementwise- Logical OR operator. It returns TRUE if one of the statement is TRUE |
| || | Logical OR operator. It returns TRUE if one of the statement is TRUE. |
| ! | Logical NOT - returns FALSE if statement is TRUE |

* * *


R Miscellaneous Operators
-------------------------

Miscellaneous operators are used to manipulate data:

| Operator | Description | Example |
| --- | --- | --- |
| : | Creates a series of numbers in a sequence | x <- 1:10 |
| %in% | Find out if an element belongs to a vector | x %in% y |
| %\*% | Matrix Multiplication | x <- Matrix1 %\*% Matrix2 |


<mark>**Note:** You will learn more about Matrix multiplication and matrices in a later chapter.</mark>